### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by jakevdp** [mmp2/megaman#19]
Ping @jmcq89 

I've been going through the package and adding some tests of corner-cases.

There are a lot of commonalities between the four embedding classes, and a lot of code that is repeated. By writing common unit tests for these, I found a number of inconsistencies with how they handle input arguments.

I think this is a case where building the four algorithms from a common base class would be *very* helpful, both in keeping the code organized & terse, and in making sure all estimators are behaving as expected.

**Comment by jmcq89** [comment]
@jakevdp Thanks Jake these are good ideas. Maybe we can discuss this a little on Thursday and plan out how I should re-factor these along with the Geometry class.

**Comment by jmcq89** [comment]
With this in mind let me know if you agree with the following:

- We should have a megaman base estimator which inherits from sklearn base estimator
- The base class should have an `__init__` which accepts *either* a geometry object *or* a dictionary with of geometry parameters including some or all of: adjacency_method adjacency_kwds, affinity_method, affinity_kwds, laplacian_method,laplacian_kwds.
- The base class should provide a fit_geometry() method -- this method should check if it's a dictionary or a geometry object and return the fitted or existing object
- The base class should provide a fit_transform() function which calls .fit() and returns .embedding_
- Individual embedding classes will then offer their own `__init__` which takes arguments specific to the embedding (e.g. n_components, drop_first, etc.) its own fit() function which calls the internal embedding function(s).
- Internal embedding functions should work with a fitted geometry object.

The embeddings will need to be re-written to handle the new Geometry API.

**Comment by mmp2** [comment]
Hi all,

We need not forget that efficiency must not be compromised. I'm fine with
this as long as the fit() operations do not duplicate storage and
evaluation.  

We need to make sure that there is the ability to recalculate similarities
and laplacians without recalculating distances when we change epsilon,
also that not all methods need the same amount of geometry (i.e only one
method needs the laplacian, others don't need the similiarity, etc).

if we encapsulate the distance matrix inside an object, then we will need
to create another geometry object in order to try a different epsilon. if
you want to do search over epsilons, something that almost anyone using
the package will have to do, they will have to drag around copies of
everything else.  or am i missing something?

cheers, 

Marina

**Comment by jmcq89** [comment]
@mmp2  summary of what we talked about. Nothing about the way data is handled is being changed just a cleaner API. 

the .fit_geometry() will only create a geometry object if you pass it a dictionary of parameters instead of an already existing geometry object. .fit_geometry() only instantiates the parameters and assigns the data matrix (or affinity matrix). This is to avoid the extra step of initializing your own geometry and passing it -- although this is still an option.

The geometry.py will still not re-compute distance matrices if a new affinity or laplacian matrix is called, however, if an existing affinity or laplacian matrix exists it *willl* be overwritten in this process. If you want to store all of these outside of the script you can pass copy = True 

Individual .fit() functions inside the embeddings will only query for necessary matrices (for example Isomap won't ask for a Laplacian matrix).

Finally, if you build a geometry object, calculate a distance matrix (or otherwise) then pass it to an embedding object and then change the original geometry object (new distance matrix or otherwise) the embedding function will use the *new* geometry as it does not copy it. See for example:

```
class Geometry(object):
	def __init__(self):
		self.distance = None
		
	def update(self,val):
		self.distance = val

class Embedding(object):
	def __init__(self, geometry):
		self.geometry = geometry
		
	def print_distance_parameter(self):
		print(self.geometry.distance)
		
if __name__ == '__main__':
	geom = Geometry() 
	geom.update(4)
	embed = Embedding(geom)	
	embed.print_distance_parameter() # the current parameter (4)
	geom.update(3) # e.g. re-calculate distance matrix 
	embed.print_distance_parameter() # embed uses the updated version (3)
```

**Comment by jmcq89** [comment]
Re-factor done.
