### ISSUE TITLE
Clean up and documentation

### ISSUE THREAD

**Issue by jmcq89** [mmp2/megaman#25]
@jakevdp @mmp2 
- [x] in SpectralEmbedding the citations are out of date -- to update 
- [x] example.py, dev_example.py, /benchmarkes/ & /astrodemo/ should be removed.
- [x] turn example.py into an iPython tutorial that we can host on the website. Perhaps we can do this as we teach the API to Grace?
- [x] The example usage & non-auto doc documentation for: Geometry, Adjacency, Laplacian, Affinity & all the embeddings need to be fixed with respect to new API changes.
- [x] The sphinx build needs to be re-run when API changes are made.
- [x] Add some example plots to the website

**Comment by mmp2** [comment]
Should we move covar_plotter.py somewhere inside the package?


Dear all, I thought of this several times, and decided not to. Because
this function is not really integrated with the package, it's just an
expedient we use for convenience. If we ever write a visualization module,
then it should belong there. But for now,given that there is no other
postprocessing or visualization functionality there, I think we can leave
it out. 

Marina
