### ISSUE TITLE
Example for performing Riemannian relaxation?

### ISSUE THREAD

**Issue by juliennelachance** [mmp2/megaman#91]
Hello,

If you get the chance, could you please provide an example to explain the usage of the function run_riemannian_relaxation()? I've utilized the code as follows: 

rr = run_riemannian_relaxation(laplacian_matrix, embed_tsne, 2, dict(niter=250, verbose=True))
rr.relax_isometry()

But am getting the following output and error:

Making Lk and nbhds
Iteration number: 0
Last step size eta: 0.0
current loss (before gradient step): 21.929018683354258
minimum loss: 21.929018683354258, at iteration: 0

Traceback (most recent call last):
  File "<file>", line 142, in <module>
    rr.relax_isometry()
  File "<path>/megaman/relaxation/riemannian_relaxation.py", line 83, in relax_isometry
    self.trace_var.update(ii,self.H,self.Y,self.eta,self.loss)
  File "<path>/megaman/relaxation/trace_variable.py", line 60, in update
    self.H[iiter] = H
IndexError: index 1 is out of bounds for axis 0 with size 1

Any guidance for performing the Riemannian relaxation would be appreciated. I've run your other example cases without problems. Thanks!

All the best,
Julienne

**Comment by yuchaz** [comment]
Hi Jelienne,

That is because `niter_trace` parameter is not specified, which turns out to be zero for default setting. And this results in writing something into a list of zero length. This will be fixed in next updates.

A quick fix is to set the `niter_trace` to `math.floor(niter / 2)`. 
Below shows an example of relaxation keywords that I used: 
```
relaxation_kwds = {
    'projected': False,
    'printiter': 1,
    'verbose': True,
    'niter': niter,
    'alpha': 0.9,
    'lossf': 'epsilon',
    'niter_trace': math.floor(niter/2),
    'eps_orth': 0.5,
    'backup_base_dir': get_config('base_dir', 'rie_output'),
    'saveiter': 250,
    'eta_max': 32,
}
```

Btw, I think it is a good to have a more detailed tutorial on this part. Thanks for this suggestion.
Let me know if you have any other questions.

Bests, Yuchia

**Comment by juliennelachance** [comment]
Hi Yuchia,

Great, thanks for the tips! I finally got it working by roughly following your relaxation keywords example. Your lab does awesome work- thanks again for your time!

Best wishes from Princeton,
-Julienne

**Comment by yuchaz** [comment]
No problems, Let me know if you have any other questions. I will close this issue now.
